import { useEffect, useLayoutEffect, useRef } from "react";
import "../global.scss";
import localFont from "next/font/local";
// import l from "../p"
// import { CustomEase, gsap, ScrollTrigger } from "@/app/lib/gsap/index";

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const rockitFont = localFont({
  src: "..//public/fonts/rockit.ttf",
});
export const iceFont = localFont({
  src: "..//public/fonts/ice.ttf",
});
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className="html" lang="en">
      <body className="body">
        {/* <div id="smooth-wrapper"> */}
        {/* <div id="smooth-content"> */}
        {children}
        {/* </div> */}
        {/* </div> */}
      </body>
    </html>
  );
}
